### ISSUE TITLE
Cannot build with Xcode 10 

### ISSUE THREAD

**Issue by mayqiyue** [esysberlin/esys-flutter-share#14]
fatal error: 'esys_flutter_share/esys_flutter_share-Swift.h' file not found
    #import <esys_flutter_share/esys_flutter_share-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by atereshkov** [comment]
Same issue here. @mayqiyue have you find the solution?

**Comment by mayqiyue** [comment]
nope, and i had choosen another plugin

Alexander Tereshkov <notifications@github.com> 于 2019年2月22日周五 22:44写道：

**Comment by atereshkov** [comment]
I found the solution. Maybe will be helpful for someone:

1. Generate new flutter app with swift template using
`flutter create -i swift my_app`
2. Copy AppDelegate.swift file
3. Remove AppDelegate.m and AppDelegate.h files
4. Add in your Podfile
`  use_frameworks!`
5. Remove Runner/main.m file
6. Add Runner-Briding-Header.h file
7. Remove libPods-Runner.a from Project settings -> General -> Embedded Binaries and from Linked Frameworks as well
8. Add Pods_runner in Linked Frameworks

And it should be okay, otherwise just copy the "ios" folder from newly generated project and replace it with "ios" folder in your project.

**Comment by atereshkov** [comment]
@mayqiyue by the way, which plugin are you using?

**Comment by gustavobrian** [comment]
Not not work!!! Any app get firebase_messaging  and firebase_messaging  requiered:
**Remove the use_frameworks! line from ios/Podfile (workaround for flutter/flutter#9694).**

**And this plug in: Add in your Podfile use_frameworks!** 

My every packages work witch out use_frameworks in podfile, where fix this problem???

please help me to fix...
and thanks for your work!!!

**Comment by d-wolf** [comment]
duplicate https://github.com/esysberlin/esys-flutter-share/issues/15
